config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :charity_associations, only: [:index] do
    collection do
      get :search
    end
  end
end

app/models/activity_code.rb
class ActivityCode < ApplicationRecord
  has_one :charity_association
  belongs_to :category

  validates :name, presence: true

  validates :code, numericality: { only_integer: true }
  validates :code, :name, uniqueness: true
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/association.rb
class Association < ActiveRecord::Base
  validates :name, :nif, :city, presence: true

  validates :nif, numericality: { only_integer: true }
  validates :nif, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :activity_codes

  validates :name, presence: true
end

app/models/charity_association.rb
class CharityAssociation < ApplicationRecord
  belongs_to :activity_code

  validates :name, :nif, :city, presence: true

  validates :nif, numericality: { only_integer: true }
  validates :nif, uniqueness: true
end

app/controllers/admin/associations_controller.rb
class Admin::AssociationsController < ApplicationController
  require 'csv'
  before_action :validate_admin_key

  def index
  end

  def import
    Association.delete_all if params[:delete_asociations_before_import]

    if file = params[:file]
      CSV.foreach(file.path, headers: true) do |row|
        name = row[1].split(' ').map { |word| word.capitalize }
        name = name.join ' '

        Association.create(nif: row[0], name: name, city: row[2])
      end

      redirect_to admin_url, notice: "Associations CSV imported."
    else
      redirect_to admin_url, notice: "Please choose a file."
    end
  end

  private

  def validate_admin_key
    session[:admin_key] ||= params[:admin_key]

    unless Rails.application.config.admin_key.eql?(session[:admin_key])
      session[:admin_key] = nil
      flash[:error] = "You must have an admin key to perform admin actions"
    end
  end
end

app/controllers/admin/charity_associations_controller.rb
class Admin::CharityAssociationsController < ApplicationController
  require 'csv'
  before_action :validate_admin_key

  def index
  end

  def import
    redirect_to admin_url, notice: 'Please choose the type of data you are uploading (IPSS or CAE).' and return if params[:info_type].blank?

    if params[:info_type].eql?('charity_associations')
      import_charity_associations_file
    elsif params[:info_type].eql?('activity_codes')
      import_activity_codes_file
    end
  end

  private

  def validate_admin_key
    session[:admin_key] ||= params[:admin_key]

    unless Rails.application.config.admin_key.eql?(session[:admin_key])
      session[:admin_key] = nil
      flash[:error] = 'You must have an admin key to perform admin actions'
    end
  end

  def import_charity_associations_file
    CharityAssociation.delete_all if params[:delete_before_import]

    if file = params[:file]
      CSV.foreach(file.path, headers: true) do |row|
        name = row[1].split(' ').map { |word| word.capitalize }
        name = name.join ' '

        CharityAssociation.create(nif: row[0], name: name, city: row[2])
      end

      redirect_to admin_url, notice: 'Charity Associations CSV imported.'
    else
      redirect_to admin_url, notice: 'Please choose a file.'
    end
  end

  def import_activity_codes_file
    ActivityCode.delete_all if params[:delete_before_import]

    if file = params[:file]
      CSV.foreach(file.path, headers: true) do |row|
        ActivityCode.create(code: row[1], name: row[2])
      end

      redirect_to admin_url, notice: 'Activity Codes CSV imported.'
    else
      redirect_to admin_url, notice: 'Please choose a file.'
    end
  end
end

app/controllers/admin/charity_associations_uploader_controller.rb
class Admin::CharityAssociationsUploaderController < ApplicationController
  require 'csv'
  before_action :authenticate_admin_user!

  def index
  end

  def import
    redirect_to admin_uploader_url, notice: 'Please choose the type of data you are uploading (IPSS or CAE).' and return if params[:info_type].blank?

    if params[:info_type].eql?('charity_associations')
      import_charity_associations_file
    elsif params[:info_type].eql?('activity_codes')
      import_activity_codes_file
    end
  end

  def import_new
    if file = params[:file]
      CSV.foreach(file.path, headers: true) do |row|
        nif = row[0]
        name = capitalize_sentence(row[1])
        city = capitalize_sentence(row[2])

        if charity_association = CharityAssociation.find_by_nif(nif)
          charity_association.name = name
          charity_association.city = city
          charity_association.save
        else
          charity_association = CharityAssociation.create(nif: nif, name: name, city: city)
        end
      end

      redirect_to admin_uploader_url, notice: 'Charity Associations NEW CSV imported.'
    else
      redirect_to admin_uploader_url, notice: 'Please choose a file.'
    end
  end

  private

  def capitalize_sentence(sentence)
    sentence = sentence.split(' ').map { |word| word.mb_chars.capitalize }
    sentence = sentence.join ' '
    sentence
  end

  def validate_admin_key
    session[:admin_key] ||= params[:admin_key]

    unless Rails.application.config.admin_key.eql?(session[:admin_key])
      session[:admin_key] = nil
      flash[:error] = 'You must have an admin key to perform admin actions'
    end
  end

  def import_charity_associations_file
    CharityAssociation.delete_all if params[:delete_before_import]

    if file = params[:file]
      CSV.foreach(file.path, headers: true) do |row|
        name = row[1].split(' ').map { |word| word.capitalize }
        name = name.join ' '

        CharityAssociation.create(nif: row[0], name: name, city: row[2])
      end

      redirect_to admin_uploader_url, notice: 'Charity Associations CSV imported.'
    else
      redirect_to admin_uploader_url, notice: 'Please choose a file.'
    end
  end

  def import_activity_codes_file
    ActivityCode.delete_all if params[:delete_before_import]

    if file = params[:file]
      CSV.foreach(file.path, headers: true) do |row|
        ActivityCode.create(code: row[1], name: row[2])
      end

      redirect_to admin_uploader_url, notice: 'Activity Codes CSV imported.'
    else
      redirect_to admin_uploader_url, notice: 'Please choose a file.'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charity_associations_controller.rb
class CharityAssociationsController < ApplicationController
  def search
    if (params[:city].blank? && params[:category_id].blank? && params[:search_term].blank?)
      return render(partial: 'search_results', locals: { message: 'Introduza termos de pesquisa, por favor.' })
    end

    chain = CharityAssociation
    chain = chain.where("lower(charity_associations.name) LIKE ?", "%#{(params[:search_term]).downcase}%") unless params[:search_term].blank?
    chain = chain.where(city: params[:city]) unless params[:city].blank?
    chain = chain.joins(:activity_code)

    unless params[:category_id].blank?
      chain = chain.where('activity_codes.category_id = ?', params[:category_id])
    end

    @charity_associations = chain

    if @charity_associations.any?
      render partial: 'search_results'
    else
      render partial: 'search_results', locals: { message: 'Não foram encontradas instituições. Tente redefinir os termos de pesquisa, por favor.' }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/associations/index.html.haml
%h1 Associations Admin

= flash[:notice]
= flash[:error]

%div
  %h3 Import a CSV File
  = form_tag admin_import_path, multipart: true do

    .fieldset
      .div
        = file_field_tag :file
        = submit_tag "Import CSV"

      .div
        = check_box_tag(:delete_asociations_before_import)
        = label_tag(:delete_asociations_before_import, "Delete existing Associations before import")

app/views/admin/charity_associations_uploader/index.html.haml
%h1 Charity Associations Admin

= flash[:notice]
= flash[:error]

%div
  %h3 Import a CSV File
  = form_tag admin_import_path, multipart: true do

    .fieldset
      .div
        = file_field_tag :file
        = submit_tag "Import CSV"

      .div
        = radio_button_tag :info_type, 'charity_associations'
        IPSS
        = radio_button_tag :info_type, 'activity_codes'
        CAE

      .div
        = check_box_tag(:delete_before_import)
        = label_tag(:delete_before_import, "Delete existing data [ipss|cae] before import")

%div
  %h3 Import a new CSV File
  = form_tag admin_import_new_path, multipart: true do

    .fieldset
      .div
        = file_field_tag :file
        = submit_tag "Import new CSV"

app/views/associations/index.html.haml
Search:
= form_tag search_associations_path, method: 'get' do
  %p
    = text_field_tag :search, params[:search]
    = submit_tag "Search"
  %p
    = radio_button_tag :search_field, 'name'
    Name
    = radio_button_tag :search_field, 'city'
    City

%table
  %thead
    %tr
      %th NIF
      %th Name
      %th City
  %tbody
    - @associations.each do |association|
      %tr
        %td= association.nif
        %td= association.name
        %td= association.city

app/views/charity_associations/_search_box.html.haml
- if flash[:notice].present?
  %p.msg.msg-notice
    = flash[:notice]

- if flash[:error].present?
  %p.msg.msg-error
  = flash[:error]

= form_tag search_charity_associations_path, method: 'get', remote: true, id: 'search' do
  %p.search-line
    %span.small-12.medium-3.large-4.field
      = text_field_tag :search_term, params[:search_term], :placeholder => "O que procura?"
    %span.small-12.medium-3.field
      %label{:class => "assist", :for => "tipo_causa"} Tipo de causa
      = select_tag :category_id, options_from_collection_for_select(Category.all.order(:name), :id, :name), :prompt => 'Todas as causas', :id => 'tipo_causa', :data => { :placeholder => 'Escolha uma causa' }
    %span.small-12.medium-3.field
      %label{:class => "assist", :for => "localidade"} Localidade
      = select_tag :city, options_for_select(CharityAssociation.order(:city).uniq.pluck(:city)), :prompt => 'Em Portugal', :id => 'localidade', :data => { :placeholder => 'Escolha uma localidade' }
    %span.small-12.medium-3.large-2
      %button{:type => "submit", :class => "button submit"} Pesquisar

  %ul#steps.steps
    %li.small-12.medium-4
      %p
        %span.icon
          %span
            %img{:src => image_path('icons/i_search.png'), :alt => '', :class => 'i-procurar'}
        %strong Pesquisar
        Encontre instituições relevantes para uma dada causa ou localização.
    %li.small-12.medium-4
      %p
        %span.icon
          %span
            %img{:src => image_path('icons/i_donate.png'), :alt => '', :class => 'i-doar'}
        %strong Doar
        Use o
        %abbr{:title => "Número de Identificação Pessoa Colectiva"} NIPC
        da instituição para doar parte do seu imposto.

    %li.small-12.medium-4
      %p
        %span.icon
          %span
            %img{:src => image_path('icons/i_heart.png'), :alt => '', :class => 'i-ajudar'}
        %strong Ajudar
        Faça a diferença, dando um apoio ao funcionamento das instituições.

app/views/charity_associations/_search_results.html.haml
.search_results
- if @charity_associations && @charity_associations.any?
  %h2.section-title #{@charity_associations.count} resultados

  .results-table
    %table
      %thead.hide-for-small
        %tr
          %th.small-5 Instituição
          %th.small-4 Causa
          %th.small-2 Localidade
          %th.small-1 NIPC
          %th
      %tbody
        - @charity_associations.each do |charity_association|
          %tr
            %td.col-instituicao{:data => { :column => "Instituição" }}= charity_association.name
            %td.col-causa{:data => { :column => "Causa" }}= charity_association.activity_code.category.name
            %td.col-localidade{:data => { :column => "Localidade" }}= charity_association.city
            %td.col-nif{:data => { :column => "NIPC" }}
              %span.nif= charity_association.nif
            %td.col-info
              %button.more-info{:data => { :nipc => charity_association.nif, :reveal_id => "ipss-info" }}
                %span.assist Como?
                %i.i-eye-plus


- else
  %p.msg.msg-notice= message

app/views/home/index.html.haml
:javascript
  $(function(){
    $('#search').on('ajax:success', function(event, data) {
      $('#search_results').html(data);
      $('#steps').html('');
    });
  });

.search-box
  .content
    = render :partial => 'charity_associations/search_box'

    #search_results.search-results

%article#ipss-info.reveal-modal{:aria_labelledby => "modalTitle", :aria_hidden => "true", :role => "dialog", :data => { :reveal => true }}
  %h2#modalTitle Como fazer?
  %p.lead
    Insira o
    %abbr{:title => "Número de Identificação de Pessoa Coletiva"} NIPC
    %span.ipss-number-place
    no
    %abbr{:title => "Benefícios Fiscais e Deduções"} Quadro 9
    do
    %abbr{:title => "Instituições Particulares de Solidariedade Social ou Pessoas Coletivas de Utilidade Pública"} Anexo H
    da Declaração do IRS.
  %p.image-preview
    %img{:src => image_path("anexoH_quadro9.png"), :alt => ""}

  %hr

  %h2 Como funciona?

  %p
    Todos os anos, ao entregar a sua declaração do IRS, tem a possibilidade de
    %b doar 0.5% do imposto total liquidado pelo Estado
    a uma Instituição de Solidariedade Social, Pessoa Colectiva de
    Utilidade Púbica ou Instituição Religiosa. Esta operação não acarreta custos para o contribuinte, nem afecta o valor
    a receber em caso de reembolso - apenas permite desviar 0.5% do imposto que entraria nos
    cofres do Estado para uma instituição escolhida pelo contribuinte. Este ato, denominado "consignação do IRS", é
    regulado pelos n.ºs 4 e 6 do artigo 32.º da Lei n.º 16/2001 de 22 de Junho.

  %p
    Este ano há a possibilidade de ajudar ainda mais. Além da doação de 0.5% do seu IRS, também tem a possibilidade de
    %b doar 15% do IVA suportado
    , em faturas de prestações de serviços comunicadas à Autoridade
    Tributária, respeitantes a quatro setores de atividades: reparação de automóveis, reparação de motociclos,
    alojamento e restauração e cabeleireiros ou institutos de beleza. O contribuinte pode assim optar por receber a
    dedução de IVA no IRS ou entregá-la a uma instituição. Neste caso já existem custos para o sujeito passivo,
    porque a contribuição é uma doação pessoal e não retirada do Estado.

  %p
    Para tal, basta preencher a sua declaração anual de IRS (em papel ou online) no
    %b quadro 9 (Benefícios Fiscais e Deduções) do anexo H (Instituições Particulares de Solidariedade Social ou Pessoas Coletivas de Utilidade Pública)
    com o número de contribuinte (NIPC) da entidade pretendida e assinalar o tipo de apoio pretendido: consignação do
    IRS, dedução do IVA ou ambos.


  %a.close-reveal-modal{:aria_label => "Close"} &#215;

%article#about-info.reveal-modal{:aria_labelledby => "modalTitle", :aria_hidden => "true", :role => "dialog", :data => { :reveal => true }}
  %h2#modalTitle Sobre o meioporcento.pt

  %p
    Este projeto procura facilitar a pesquisa de entidades elegíveis ao benefício fiscal da consignação de quota do IRS
    e dedução do IVA. Aqui, qualquer contribuinte pode encontrar uma entidade à qual doar parte do seu imposto através
    de uma pesquisa simples, focada na causa ou localização das entidades.

  %p
    A lista de entidades aqui apresentada foi obtida no
    = link_to 'Portal das Finanças', 'http://info.portaldasfinancas.gov.pt/NR/rdonlyres/001D01F0-19AA-4942-A54E-7BE37A7C3DA9/0/Consignacao_colecta_IRS_Lista_entidades.xls', target: '_blank'
    (última atualização 26-02-2015).

    As causas das organizações foram inferidas através de informação disponível no
    = link_to 'Sistema Informação de Classificação Portuguesa de Atividades Económicas', 'http://www.sicae.pt/'
    = '.'
    Os dados aqui apresentados são relativos à entrega do IRS em 2015 (ano fiscal de 2014).

  %p
    Este projeto não tem fins lucrativos. O código fonte utilizado é aberto (open-source) e está disponível no
    = link_to 'GitHub', 'https://github.com/bmccoelho/taxes-for-charity'
    = '.'
    Este projeto foi desenvolvido por
    <a href="https://twitter.com/andr3">André Luís</a>,
    <a href="https://twitter.com/brunocruzcoelho">Bruno Coelho</a>,
    <a href="https://twitter.com/Leihla">Leihla Pinho</a>,
    <a href="https://twitter.com/Marie_Furtado">Maria Furtado</a> e
    <a href="https://twitter.com/marionzualo">Mário Nzualo</a>.

  %p
    Para questões relacionadas com o projecto, contacte-nos através do e-mail
    = mail_to 'meioporcento.pt@gmail.com'
    = '.'
    Pode também receber atualizações do projeto no
    = link_to 'Facebook', 'https://www.facebook.com/meioporcentopt'
    e no
    = link_to 'Twitter', 'https://twitter.com/meioporcento_pt'
    = '.'

  %a.close-reveal-modal{:aria_label => "Close"} &#215;

app/views/home/teaser.html.haml
- content_for(:title) do
  meioporcento.pt — Brevemente...

- content_for(:subtitles) do
  .assist

.search-box
  .content
    %p.text-center Brevemente para a temporada fiscal relativa a 2014.

app/views/layouts/application.html.haml
!!! Strict
:plain
  <!--[if lte IE 8]><html lang="en-US" class="no-js ie8andlower ie8"><![endif]-->
  <!--[if IE 9]><html lang="en-US" class="no-js ie9"><![endif]-->
  <!--[if !IE]><!--><html lang="en-US" class="no-js"><!--<![endif]-->
%head
  %title Meio Por Cento
  %meta{:name => "viewport", :content => "width=device-width,initial-scale=1"}
  %meta{:name => "description", :content => "Reverta 0.5% do seu IRS e/ou 15% de parte do seu IVA suportado a uma instituição de cariz social"}
  %meta{:name => "keywords", :content => "consignação irs iva impostos irs2014 irs2015 anexoH modelo3 IPSS instituição particular de solidariedade social cariz social"}
  %meta{:"http-equiv" => "X-UA-Compatible", :content => "IE=edge,Chrome=1"}

  %link{:rel => "shortcut icon", :type => "image/x-icon", :href => "/favicon.ico"}
  %link{:rel => "apple-touch-icon", :href => image_path("icons/touch-icon-76.png")}
  %link{:rel => "apple-touch-icon", :sizes => "76x76", :href => image_path("icons/touch-icon-76.png")}
  %link{:rel => "apple-touch-icon", :sizes => "120x120", :href => image_path("icons/touch-icon-120.png")}
  %link{:rel => "apple-touch-icon", :sizes => "152x152", :href => image_path("icons/touch-icon-152.png")}

  %meta{:property => "og:title", :content => "Meio Por Cento"}
  %meta{:property => "og:type", :content => "website"}
  %meta{:property => "og:url", :content => "http://www.meioporcento.pt/"}
  %meta{:property => "og:image", :content => "http://www.meioporcento.pt" + image_path("opengraph.png")}
  %meta{:property => "og:description", :content => "Este projeto procura facilitar a pesquisa de entidades elegíveis ao benefício fiscal da consignação de quota do IRS e dedução do IVA. Aqui, o contribuinte pode, através da causa ou localização, encontrar a entidade a quem doar parte do seu imposto."}

  = stylesheet_link_tag("application.css")
  = stylesheet_link_tag("small.css", :media => "only screen and (max-width: 40.063em)")

  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

  %script{:src => "//use.typekit.net/twz1zse.js"}
  %script try{Typekit.load();}catch(e){}
- body_classes = params[:action].present? ? "action-#{params[:action]}" : ""
%body{:class => body_classes}
  %header.site-header
    .content
      - if true
        %h1.site-title.site-title-graphic<>
          %a.site-root{:href => root_path}
            %span meio por cento
      - else
        %h1.site-title<>
          %a.site-root{:href => root_path}
            %span meio por cento

      - if content_for?(:subtitles)
        = yield(:subtitles)
      - else
        %p.sub-sub-title
          A forma mais fácil de ajudar.
          Reverta
          %b 0.5%
          do seu
          %abbr{:title => "Imposto sobre o Rendimento das Pessoas Singulares"} IRS
          e/ou
          %b 15%
          de parte do seu
          %abbr{:title => "Imposto sobre o Valor Acrescentado"}IVA
          suportado para uma instituição de cariz social.
    %nav
      %ul
        %li
          %a{:href => "#about-info", :data => { :reveal_id => "about-info" }} Sobre
        %li
          %a{:href => "#ipss-info", :data => { :reveal_id => "ipss-info" }} Como funciona?

  = yield

  %footer.content.text-center
    &copy; 2015 — meioporcento.pt

  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '#{Rails.application.config.google_analytics_key}', 'auto');
    ga('send', 'pageview');